from dataclasses import dataclass

import torch
from torch import nn

from spacetime.models.genie.config import DynamicsConfig, LamConfig
from spacetime.models.genie.dynamics import DynamicsModel
from spacetime.models.genie.latent_actions import LatentActionModel
from spacetime.models.tokenizer.config import TokenizerConfig
from spacetime.models.tokenizer.model import VQTokenizer


@dataclass
class GenieOutput:
    lam_reconstruction: torch.Tensor
    z_e: torch.Tensor
    actions: torch.Tensor
    output_tokens: torch.Tensor
    token_indices: torch.Tensor
    token_embeddings: torch.Tensor


class GenieModel(nn.Module):
    """
    Genie: Generative Interactive Environments, Bruce et. al. 2024

    Model wrapper: pretrained tokenizer, and learnable latent action + dynamics models.
    """

    def __init__(
        self,
        lam_cfg: LamConfig,
        dyn_cfg: DynamicsConfig,
        tokenizer_cfg: TokenizerConfig,
        pretrained_tokenizer: VQTokenizer,
    ) -> None:
        super().__init__()

        self.lam = LatentActionModel(lam_cfg)
        self.dynamics = DynamicsModel(
            dynamics_cfg=dyn_cfg,
            lam_cfg=lam_cfg,
            tokenizer_cfg=tokenizer_cfg,
        )
        self.tokenizer = pretrained_tokenizer

    def forward(self, x: torch.Tensor) -> GenieOutput:
        """
        This is what a full forward pass looks like (language description since this is the crux of it all):

        A1

        input video frames [B, C, F, H, W] -> tokenizer -> encoder outputs, quantized

        what do we care about from the tokenizer? tokens! Thus, all we want to run a forward pass
        over is the encoder, and quantize them. this will be passed to the dynamics model as one piece
        of its inputs

        A2

        at the same time,
        input video frames [B, C, F, H, W] -> latent action model

        here, we care about both the encoder and decoder outputs. encoder outputs once quantized
        (actions) are used as input to the dynamics model. they are optimized as part of the decoder loss as well
        as the dynamics models loss. the decoder outputs are stored to run standard vq vae loss (includeing recon)
        to provide additional training signal

        B

        The Dynamics model takes in tokens (spatiotemporal as well as action) from the models and runs generative
        inference. its outputs are stored so that we can compute loss for the generation -- the main objective.

        Thus, we return vq vae encoder and decoder outputs for reconstruction + commitment loss, as well as the
        frame generated by the dynamics model
        """
        with torch.no_grad():
            token_embeddings, token_indices, _ = self.tokenizer.tokenize(x)

        lam_reconstruction, z_e, actions = self.lam(x)
        output_tokens = self.dynamics(token_embeddings, actions)

        return GenieOutput(
            lam_reconstruction=lam_reconstruction,
            z_e=z_e,
            actions=actions,
            output_tokens=output_tokens,
            token_indices=token_indices,
            token_embeddings=token_embeddings,
        )
