import torch
from torch import nn

from spacetime.models.dynamics_model.dynamics_model import DynamicsModel
from spacetime.models.genie.config import DynamicsConfig, LamConfig
from spacetime.models.latent_actions.model import LatentActionModel
from spacetime.models.tokenizer.config import TokenizerConfig
from spacetime.models.tokenizer.model import VQTokenizer


class GenieModel(nn.Module):
    """
    Genie
    """
    def __init__(
        self,
        lam_cfg: LamConfig,
        dyn_cfg: DynamicsConfig,
        tokenizer_cfg: TokenizerConfig,
        pretrained_tokenizer: VQTokenizer,
    ) -> None:
        super().__init__()

        self.lam = LatentActionModel(
            num_heads=lam_cfg.num_heads,
            d_model=lam_cfg.d_model,
            num_layers=lam_cfg.num_layers,
            d_linear=lam_cfg.d_linear,
            num_discrete_actions=lam_cfg.num_discrete_actions,
            codebook_dim=lam_cfg.codebook_dim,
            patch_size=lam_cfg.patch_size,
            frame_height=lam_cfg.frame_height,
            frame_width=lam_cfg.frame_width,
            num_frames=lam_cfg.num_frames,
            num_linear_layers=lam_cfg.num_linear_layers,
            num_groups=lam_cfg.num_groups,
            dropout=lam_cfg.dropout,
        )
        self.dynamics = DynamicsModel(
            dynamics_cfg=dyn_cfg,
            lam_cfg=lam_cfg,
            tokenizer_cfg=tokenizer_cfg,
        )
        self.tokenizer = pretrained_tokenizer

    def forward(
        self,
        x: torch.Tensor
    ) -> dict[str, torch.Tensor]:
        """
        This is what a full forward pass looks like (language description since this is the crux of it all): 

        A1

        input video frames [B, F, C, H, W] -> tokenizer -> encoder outputs, quantized

        what do we care about from the tokenizer? tokens! Thus, all we want to run a forward pass 
        over is the encoder, and quantize them. this will be passed to the dynamics model as one piece
        of its inputs 

        to be figured out: how can we perform surgery on this model such that we don't run a full forward pass

        A2

        at the same time, 


        input video frames [B, F, C, H, W] -> latent action model

        here, we care about both the encoder and decoder outputs. encoder outputs once quantized
        (actions) are used as input to the dynamics model. they are optimized as part of the decoder loss as well 
        as the dynamics models loss. the decoder outputs are stored to run standard vq vae loss (includeing recon)
        to provide additional training signal 

        B

        The Dynamics model takes in tokens (spatiotemporal as well as action) from the models and runs generative
        inference. its outputs are stored so that we can compute loss for the generation -- the main objective. 

        Thus, we return vq vae encoder and decoder outputs for reconstruction + commitment loss, as well as the 
        frame generated by the dynamics model 
        
        """
        
